### ISSUE TITLE
Login Details

### ISSUE THREAD

**Issue by OpenCV-Peter** [alphafox02/antsdr_dji_droneid#3]
Interesting project, thank you for sharing it. I managed to get the DJI DroneID via Kismet and directly via Python.

Could you share the login details? I like to log in with SSH and have a look at what is running on the ANTSDR E200.

**Comment by alphafox02** [comment]
Try abawavearm as the password, it’s been so long I had to search back in chat history to find it mentioned. I’m not sure if it’s root as the user though.

**Comment by OpenCV-Peter** [comment]
Thanks. The login is indeed:

User: root
Password: abawavearm
