### ISSUE TITLE
Distance of detection

### ISSUE THREAD

**Issue by OP-drone** [alphafox02/antsdr_dji_droneid#5]
Who tested what a maximal distance of detection ?

I tested with omni antenna 11dB = range only 300 meters in urban.

**Comment by alphafox02** [comment]
Tech minds on YouTube did some longer range testing if I recall. I’ve since switched to detecting “Remote ID”, specifically the bt5 long range type. I received it 1km away but that was across a lake. I’ll go back out with my dji and try again with my AntSDR e200 and see what kind of range I can get.

Did you have line of sight?

**Comment by OP-drone** [comment]
In my test I had full line of sight.

“Remote ID" and "DJI Remote ID" are different protocols.
"Remote ID" from the FAA (Federal Aviation Administration) works in US airspace and the drone fw should support this.
 "DJI Remote ID" works all over the world.

**Comment by OP-drone** [comment]
Nobody tested the detection range?

**Comment by alphafox02** [comment]
https://youtu.be/4F0T7_sB_Ss?si=3NUiZyyB0lAS6hPX

**Comment by Tissy** [comment]
Any further insights into this please?  As the firmware is not open source, I am wondering if there any additional opportunities to increase the gain / sweep rate of the SDR to improve performance?  I'd be interested in any range / model testing anyone has done.

Many thanks.

**Comment by alphafox02** [comment]
You could ssh in and perhaps change gain somewhere? But I’d better take a look. I think progress stopped due to dji encrypting the droneid on some drones now?

**Comment by Tissy** [comment]
That would be great to test if possible.  Happy to do the field testing if you can point to where the changes need to be made.

DJI have started encrypting DroneID on some models, but not all and this capability is still very much relevant.

Would be great if Yaw and UUID can also be added as per https://github.com/alphafox02/antsdr_dji_droneid/issues/4 :)

More than happy to help contribute to development in anyway I can.
